import type { Env } from "./types";
import { isLockedFactPath } from "../../../shared/locked-fact-files";
import type { AgentEditFixContext } from "../../../shared/design-fix-loop";
import { DESIGN_ICON_URLS } from "../../../shared/design-web-images";
import {
  AGENT_EDIT_JSON_RETRY_NUDGE,
  MAX_PARSE_RETRIES,
  parseAgentEditFromText,
} from "./agent-edit-parse";
import { requireApprovedDesignRequest } from "./approve-design-request";
import { resolveWebAssets } from "./fetch-web-asset";
import {
  openRouterChat,
  resolveOpenRouterModel,
  type ChatMessage,
  type OpenRouterChatResult,
} from "./openrouter";

export type AgentEditInput = {
  prompt: string;
  selectedElement?: {
    designId?: string;
    tagName?: string;
    text?: string;
    selector?: string;
    sourceFile?: string;
  } | null;
  files: Record<string, string>;
  fixContext?: AgentEditFixContext | null;
};

export type AgentEditWrite = {
  path: string;
  content: string;
};

export type AgentEditResult = {
  summary: string;
  writes: AgentEditWrite[];
  commands: string[];
  assets?: Array<{ url: string; path: string }>;
};

export type AgentEditStreamEmit = (event: string, data: Record<string, unknown>) => void;

const EDIT_SYSTEM_PROMPT = `You are a code editing assistant for popped.dev — a Next.js community portfolio.
Return ONLY one valid JSON object (no markdown fences, no commentary).
The JSON must match this shape:
{
  "summary": "<one sentence>",
  "writes": [{ "path": "src/app/design-overrides.css", "content": "<full file content>" }],
  "commands": [],
  "assets": []
}

Rules:
- For simple color, size, spacing, or border tweaks: ONLY append CSS to src/app/design-overrides.css — keep the response small.
- Visual AND functional changes are allowed: styling, layout, links, buttons, navigation, new components, interactivity, section order, social link rows, tooltips, etc.
- Return FULL file contents for each write (not diffs). Prefer one file when possible.
- NEVER modify locked fact files: src/locked/experience.json, src/locked/*, src/components/locked/LockedIntro.tsx.
- NEVER write src/components/locked/LockedResume.tsx — style resume sections via src/app/design-overrides.css using [data-design-id="..."] selectors, or add community components under src/components/community/.
- You MAY read src/locked/experience.json for facts (name, links, skills, projects) and display them in new community TSX — but never change the JSON.
- Prefer src/app/design-overrides.css, src/components/community/*, src/app/globals.css, src/components/SiteHeader.tsx.
- Icons and images:
  - Use img src with HTTPS CDN URLs directly (works without downloading): ${Object.entries(DESIGN_ICON_URLS).map(([k, v]) => `${k}=${v}`).join(", ")}
  - Or list assets[] to fetch into public/assets/ (allowlisted hosts: cdn.simpleicons.org, raw.githubusercontent.com, github.githubassets.com, avatars.githubusercontent.com)
  - Or inline SVG / Unicode emoji in TSX. Do not use npm icon libraries unless the user explicitly asks.
- commands: only npm install lines if new packages are needed; otherwise [].
- Keep changes minimal and focused on the user request.`;

const FIX_SYSTEM_PROMPT = `You fix compile/build errors in popped.dev — a Next.js community portfolio.
A previous AI edit broke the preview. Return ONLY one valid JSON object (no markdown fences):
{
  "summary": "<one sentence>",
  "writes": [{ "path": "src/app/design-overrides.css", "content": "<full corrected file content>" }],
  "commands": [],
  "assets": []
}

Rules:
- Fix the reported error with the smallest correct change.
- Return FULL file contents for each write (not diffs).
- NEVER modify locked fact files: src/locked/experience.json, src/locked/*, src/components/locked/LockedIntro.tsx.
- NEVER write src/components/locked/LockedResume.tsx.
- Prefer fixing the files that caused the error; use src/app/design-overrides.css, src/components/community/*, src/app/globals.css, src/components/SiteHeader.tsx.
- If imports or syntax are wrong, fix them. If a package is missing, add npm install in commands.
- Do not introduce unrelated changes.`;

function buildEditPrompt(input: AgentEditInput): string {
  const fileList = Object.keys(input.files)
    .slice(0, 20)
    .map((path) => `- ${path}`)
    .join("\n");

  const fileContents = Object.entries(input.files)
    .slice(0, 4)
    .map(([path, content]) => `### ${path}\n\`\`\`\n${content.slice(0, 1200)}\n\`\`\``)
    .join("\n\n");

  const element = input.selectedElement
    ? JSON.stringify(input.selectedElement, null, 2)
    : "null";

  const experience = input.files["src/locked/experience.json"];
  const experienceBlock = experience
    ? `\nResume facts (read-only — do not edit this file):\n\`\`\`json\n${experience.slice(0, 2000)}\n\`\`\`\n`
    : "";

  return `Selected element:
${element}

Available files:
${fileList}

File contents (subset):
${fileContents}
${experienceBlock}
User request:
${input.prompt}`;
}

function buildFixPrompt(input: AgentEditInput): string {
  const fix = input.fixContext;
  if (!fix) return buildEditPrompt(input);

  const fileList = Object.keys(input.files)
    .slice(0, 24)
    .map((path) => `- ${path}`)
    .join("\n");

  const fileContents = Object.entries(input.files)
    .slice(0, 6)
    .map(([path, content]) => `### ${path}\n\`\`\`\n${content.slice(0, 2000)}\n\`\`\``)
    .join("\n\n");

  const element = input.selectedElement
    ? JSON.stringify(input.selectedElement, null, 2)
    : "null";

  return `Fix attempt ${fix.attempt} of ${fix.maxAttempts}.

Original user request:
${fix.originalPrompt ?? input.prompt}

Compile/build error:
${fix.compileError}

Selected element:
${element}

Available files:
${fileList}

Current file contents (includes broken state):
${fileContents}

Return corrected files that fix the error.`;
}

function fallbackEdit(input: AgentEditInput): AgentEditResult {
  const overridesPath = "src/app/design-overrides.css";
  const existing = input.files[overridesPath] ?? `/* design overrides */\n`;
  const designId = input.selectedElement?.designId;
  const lower = input.prompt.toLowerCase();
  let cssRule = "outline: 2px solid #2563eb; outline-offset: 4px;";

  if (lower.includes("red")) cssRule = "color: #dc2626 !important;";
  else if (lower.includes("blue")) cssRule = "color: #2563eb !important;";
  else if (lower.includes("green")) cssRule = "color: #16a34a !important;";
  else if (lower.includes("big") || lower.includes("large")) cssRule = "font-size: 1.25em !important;";
  else if (lower.includes("small")) cssRule = "font-size: 0.875em !important;";
  else if (lower.includes("bold")) cssRule = "font-weight: 700 !important;";
  else if (lower.includes("dark")) cssRule = "background: #111 !important; color: #fafafa !important;";

  const selector = designId
    ? `#locked-resume [data-design-id="${designId}"], [data-design-id="${designId}"]`
    : "body";

  const block = `\n/* agent fallback */\n${selector} {\n  ${cssRule}\n}\n`;

  return {
    summary: designId
      ? `Styled ${designId} with a visible fallback change.`
      : "Applied a visible CSS override as a fallback edit.",
    writes: [{ path: overridesPath, content: existing + block }],
    commands: [],
  };
}

function isSafeAgentWritePath(path: string): boolean {
  if (isLockedFactPath(path)) return false;
  if (path.startsWith("src/components/locked/")) return false;
  if (path.startsWith("src/locked/")) return false;
  if (path === "src/app/design-overrides.css") return true;
  if (path === "src/app/globals.css") return true;
  if (path.startsWith("src/components/community/")) return true;
  if (path === "src/components/SiteHeader.tsx") return true;
  if (path.startsWith("public/assets/")) return true;
  return false;
}

async function finalizeAgentEditResult(
  result: AgentEditResult,
  input: AgentEditInput,
  strict = false,
): Promise<AgentEditResult> {
  const sanitized = sanitizeAgentEditResult(result, input, strict);

  if (!result.assets?.length) return sanitized;

  const fetched = await resolveWebAssets(result.assets);
  if (fetched.length === 0) return sanitized;

  const writes = [...sanitized.writes];
  for (const asset of fetched) {
    if (!writes.some((write) => write.path === asset.path)) {
      writes.push({ path: asset.path, content: asset.content });
    }
  }

  return { ...sanitized, writes };
}

function sanitizeAgentEditResult(
  result: AgentEditResult,
  input: AgentEditInput,
  strict = false,
): AgentEditResult {
  const safeWrites = result.writes.filter((write) => isSafeAgentWritePath(write.path));
  const safeCommands = result.commands.filter((cmd) => cmd.trim().startsWith("npm install"));

  if (strict && result.writes.length > 0 && safeWrites.length === 0) {
    throw new Error("The AI tried to edit locked files — try styling with CSS instead.");
  }

  if (safeWrites.length > 0) {
    return { summary: result.summary, writes: safeWrites, commands: safeCommands };
  }

  const fallback = fallbackEdit(input);
  return {
    summary: result.summary || fallback.summary,
    writes: fallback.writes,
    commands: [],
  };
}

function openRouterErrorMessage(result: OpenRouterChatResult): string {
  if (!result.error) return "OpenRouter did not return an edit.";
  if (result.status === 402 || /credits|afford|402/.test(result.error)) {
    return "OpenRouter is out of credits on this API key — add credits at openrouter.ai/settings/keys or raise the key's daily limit.";
  }
  return `OpenRouter did not return an edit. ${result.error}`;
}

async function callDesignLlm(
  env: Env,
  messages: ChatMessage[],
): Promise<OpenRouterChatResult> {
  return openRouterChat(env, messages, {
    maxTokens: 2048,
    temperature: 0.15,
  });
}

async function runLlmEditPass(
  env: Env,
  input: AgentEditInput,
  emit: AgentEditStreamEmit | undefined,
  options: { systemPrompt: string; userPrompt: string; strict: boolean },
): Promise<AgentEditResult> {
  const model = resolveOpenRouterModel(env);
  const hasOpenRouter = Boolean(env.OPENROUTER_API_KEY?.trim());

  if (hasOpenRouter) {
    emit?.("status", { message: `Agent is working… (${model})`, model });
  }

  let messages: ChatMessage[] = [
    { role: "system", content: options.systemPrompt },
    { role: "user", content: options.userPrompt },
  ];

  let lastRawText: string | null = null;

  for (let attempt = 0; attempt <= MAX_PARSE_RETRIES; attempt += 1) {
    const aiResult = await callDesignLlm(env, messages);

    if (hasOpenRouter && !aiResult.text) {
      throw new Error(openRouterErrorMessage(aiResult));
    }

    if (!aiResult.text) break;

    lastRawText = aiResult.text;
    const parsed = parseAgentEditFromText(aiResult.text);
    if (parsed) {
      emit?.("status", { message: "Edit ready — applying…", model });
      return finalizeAgentEditResult(parsed, input, options.strict);
    }

    if (attempt < MAX_PARSE_RETRIES) {
      emit?.("status", {
        message: `Retrying — fixing response format (${attempt + 1}/${MAX_PARSE_RETRIES})…`,
        model,
      });
      messages = [
        ...messages,
        { role: "assistant", content: aiResult.text.slice(0, 1200) },
        { role: "user", content: AGENT_EDIT_JSON_RETRY_NUDGE },
      ];
    }
  }

  if (!hasOpenRouter) {
    emit?.("status", { message: "Using fallback edit…" });
    return fallbackEdit(input);
  }

  if (!input.fixContext) {
    console.warn("Agent edit parse failed, using CSS fallback. Raw:", lastRawText?.slice(0, 400));
    emit?.("status", { message: "Using CSS fallback…" });
    return fallbackEdit(input);
  }

  throw new Error(
    "The AI returned an invalid fix — the build error may need a manual tweak.",
  );
}

export async function runAgentEdit(
  env: Env,
  input: AgentEditInput,
  emit?: AgentEditStreamEmit,
): Promise<AgentEditResult> {
  if (!input.prompt.trim()) {
    throw new Error("Prompt is required.");
  }
  if (Object.keys(input.files).length === 0) {
    throw new Error("No project files provided.");
  }

  if (input.fixContext) {
    const { attempt, maxAttempts } = input.fixContext;
    emit?.("status", {
      message: `Fixing build error (${attempt}/${maxAttempts})…`,
      fixAttempt: attempt,
      maxFixAttempts: maxAttempts,
    });

    return runLlmEditPass(env, input, emit, {
      systemPrompt: FIX_SYSTEM_PROMPT,
      userPrompt: buildFixPrompt(input),
      strict: true,
    });
  }

  await requireApprovedDesignRequest(env, input, emit);

  return runLlmEditPass(env, input, emit, {
    systemPrompt: EDIT_SYSTEM_PROMPT,
    userPrompt: buildEditPrompt(input),
    strict: true,
  });
}
