import type { Env } from "./types";
import {
  buildProjectTreeSummary,
  orderAgentContextPaths,
} from "../../../shared/agent-context-files";
import {
  buildEditSystemPrompt,
  buildFixSystemPrompt,
} from "../../../shared/agent-edit-prompts";
import { isEditableWorkspacePath } from "../../../shared/editable-workspace-paths";
import type { AgentEditFixContext } from "../../../shared/design-fix-loop";
import {
  AGENT_EDIT_JSON_RETRY_NUDGE,
  MAX_PARSE_RETRIES,
  parseAgentEditFromText,
} from "./agent-edit-parse";
import { requireApprovedDesignRequest } from "./approve-design-request";
import { resolveWebAssets } from "./fetch-web-asset";
import {
  openRouterChat,
  resolveOpenRouterModel,
  type ChatMessage,
  type OpenRouterChatResult,
} from "./openrouter";

export type AgentEditInput = {
  prompt: string;
  selectedElement?: {
    designId?: string;
    tagName?: string;
    text?: string;
    selector?: string;
    sourceFile?: string;
  } | null;
  files: Record<string, string>;
  fixContext?: AgentEditFixContext | null;
};

export type AgentEditWrite = {
  path: string;
  content: string;
};

export type AgentEditResult = {
  summary: string;
  writes: AgentEditWrite[];
  commands: string[];
  assets?: Array<{ url: string; path: string }>;
};

export type AgentEditStreamEmit = (event: string, data: Record<string, unknown>) => void;

function buildEditPrompt(input: AgentEditInput): string {
  const sourceFile = input.selectedElement?.sourceFile;
  const orderedPaths = orderAgentContextPaths(input.files, sourceFile);
  const treeSummary = buildProjectTreeSummary(input.files);

  const fileList = orderedPaths.map((path) => `- ${path}`).join("\n");

  const fileContents = orderedPaths
    .map((path) => `### ${path}\n\`\`\`\n${input.files[path]}\n\`\`\``)
    .join("\n\n");

  const element = input.selectedElement
    ? JSON.stringify(input.selectedElement, null, 2)
    : "null";

  const experience = input.files["src/locked/experience.json"];
  const experienceBlock = experience
    ? `\nResume facts (read-only — do not edit this file):\n\`\`\`json\n${experience.slice(0, 3000)}\n\`\`\`\n`
    : "";

  return `Project structure:
${treeSummary}

Selected element:
${element}

Available files (${orderedPaths.length}):
${fileList}

File contents:
${fileContents}
${experienceBlock}
User request:
${input.prompt}`;
}

function buildFixPrompt(input: AgentEditInput): string {
  const fix = input.fixContext;
  if (!fix) return buildEditPrompt(input);

  const sourceFile = input.selectedElement?.sourceFile;
  const orderedPaths = orderAgentContextPaths(input.files, sourceFile);

  const fileList = orderedPaths.map((path) => `- ${path}`).join("\n");

  const fileContents = orderedPaths
    .map((path) => `### ${path}\n\`\`\`\n${input.files[path]}\n\`\`\``)
    .join("\n\n");

  const element = input.selectedElement
    ? JSON.stringify(input.selectedElement, null, 2)
    : "null";

  return `Fix attempt ${fix.attempt} of ${fix.maxAttempts}.

Original user request:
${fix.originalPrompt ?? input.prompt}

Compile/build error:
${fix.compileError}

Selected element:
${element}

Available files:
${fileList}

Current file contents (includes broken state):
${fileContents}

Return corrected files in a <boltArtifact> or JSON writes array.`;
}

function fallbackEdit(input: AgentEditInput): AgentEditResult {
  const overridesPath = "src/app/design-overrides.css";
  const existing = input.files[overridesPath] ?? `/* design overrides */\n`;
  const designId = input.selectedElement?.designId;
  const lower = input.prompt.toLowerCase();
  let cssRule = "outline: 2px solid #2563eb; outline-offset: 4px;";

  if (lower.includes("red")) cssRule = "color: #dc2626 !important;";
  else if (lower.includes("blue")) cssRule = "color: #2563eb !important;";
  else if (lower.includes("green")) cssRule = "color: #16a34a !important;";
  else if (lower.includes("big") || lower.includes("large")) cssRule = "font-size: 1.25em !important;";
  else if (lower.includes("small")) cssRule = "font-size: 0.875em !important;";
  else if (lower.includes("bold")) cssRule = "font-weight: 700 !important;";
  else if (lower.includes("dark")) cssRule = "background: #111 !important; color: #fafafa !important;";

  const selector = designId
    ? `#locked-resume [data-design-id="${designId}"], [data-design-id="${designId}"]`
    : "body";

  const block = `\n/* agent fallback */\n${selector} {\n  ${cssRule}\n}\n`;

  return {
    summary: designId
      ? `Styled ${designId} with a visible fallback change.`
      : "Applied a visible CSS override as a fallback edit.",
    writes: [{ path: overridesPath, content: existing + block }],
    commands: [],
  };
}

function isSafeAgentWritePath(path: string): boolean {
  return isEditableWorkspacePath(path);
}

async function finalizeAgentEditResult(
  result: AgentEditResult,
  input: AgentEditInput,
  strict = false,
): Promise<AgentEditResult> {
  const sanitized = sanitizeAgentEditResult(result, input, strict);

  if (!result.assets?.length) return sanitized;

  const fetched = await resolveWebAssets(result.assets);
  if (fetched.length === 0) return sanitized;

  const writes = [...sanitized.writes];
  for (const asset of fetched) {
    if (!writes.some((write) => write.path === asset.path)) {
      writes.push({ path: asset.path, content: asset.content });
    }
  }

  return { ...sanitized, writes };
}

function sanitizeAgentEditResult(
  result: AgentEditResult,
  input: AgentEditInput,
  strict = false,
): AgentEditResult {
  const safeWrites = result.writes.filter((write) => isSafeAgentWritePath(write.path));
  const safeCommands = result.commands.filter((cmd) => {
    const trimmed = cmd.trim();
    return trimmed.startsWith("npm install") || trimmed.startsWith("npm i ");
  });

  if (strict && result.writes.length > 0 && safeWrites.length === 0) {
    throw new Error(
      "The AI tried to edit locked files — pick a different approach that avoids locked fact paths.",
    );
  }

  if (safeWrites.length > 0 || safeCommands.length > 0) {
    return { summary: result.summary, writes: safeWrites, commands: safeCommands };
  }

  if (strict) {
    throw new Error(
      "The AI returned no editable file changes. Try rephrasing your request with more detail.",
    );
  }

  const fallback = fallbackEdit(input);
  return {
    summary: result.summary || fallback.summary,
    writes: fallback.writes,
    commands: [],
  };
}

function openRouterErrorMessage(result: OpenRouterChatResult): string {
  if (!result.error) return "OpenRouter did not return an edit.";
  if (result.status === 402 || /credits|afford|402/.test(result.error)) {
    return "OpenRouter is out of credits on this API key — add credits at openrouter.ai/settings/keys or raise the key's daily limit.";
  }
  return `OpenRouter did not return an edit. ${result.error}`;
}

async function callDesignLlm(
  env: Env,
  messages: ChatMessage[],
  maxTokens = 32_768,
): Promise<OpenRouterChatResult> {
  return openRouterChat(env, messages, {
    maxTokens,
    temperature: 0.15,
  });
}

async function runLlmEditPass(
  env: Env,
  input: AgentEditInput,
  emit: AgentEditStreamEmit | undefined,
  options: { systemPrompt: string; userPrompt: string; strict: boolean },
): Promise<AgentEditResult> {
  const model = resolveOpenRouterModel(env);
  const hasOpenRouter = Boolean(env.OPENROUTER_API_KEY?.trim());

  if (hasOpenRouter) {
    emit?.("status", { message: `Agent is planning & building… (${model})`, model });
  }

  let messages: ChatMessage[] = [
    { role: "system", content: options.systemPrompt },
    { role: "user", content: options.userPrompt },
  ];

  let lastRawText: string | null = null;

  for (let attempt = 0; attempt <= MAX_PARSE_RETRIES; attempt += 1) {
    const aiResult = await callDesignLlm(
      env,
      messages,
      options.strict ? 32_768 : 24_576,
    );

    if (hasOpenRouter && !aiResult.text) {
      throw new Error(openRouterErrorMessage(aiResult));
    }

    if (!aiResult.text) break;

    lastRawText = aiResult.text;
    const parsed = parseAgentEditFromText(aiResult.text);
    if (parsed) {
      const fileCount = parsed.writes.length;
      emit?.("status", {
        message:
          fileCount > 0
            ? `Ready — ${fileCount} file${fileCount === 1 ? "" : "s"} to apply…`
            : "Edit ready — applying…",
        model,
      });
      return finalizeAgentEditResult(parsed, input, options.strict);
    }

    if (attempt < MAX_PARSE_RETRIES) {
      emit?.("status", {
        message: `Retrying — fixing response format (${attempt + 1}/${MAX_PARSE_RETRIES})…`,
        model,
      });
      messages = [
        ...messages,
        { role: "assistant", content: aiResult.text.slice(0, 2000) },
        { role: "user", content: AGENT_EDIT_JSON_RETRY_NUDGE },
      ];
    }
  }

  if (!hasOpenRouter) {
    emit?.("status", { message: "Using fallback edit…" });
    return fallbackEdit(input);
  }

  if (!input.fixContext) {
    console.warn("Agent edit parse failed. Raw:", lastRawText?.slice(0, 600));
    throw new Error(
      "The AI could not produce a valid edit. Try rephrasing — be specific about what you want built or changed.",
    );
  }

  throw new Error(
    "The AI returned an invalid fix — the build error may need a manual tweak.",
  );
}

export async function runAgentEdit(
  env: Env,
  input: AgentEditInput,
  emit?: AgentEditStreamEmit,
): Promise<AgentEditResult> {
  if (!input.prompt.trim()) {
    throw new Error("Prompt is required.");
  }
  if (Object.keys(input.files).length === 0) {
    throw new Error("No project files provided.");
  }

  if (input.fixContext) {
    const { attempt, maxAttempts } = input.fixContext;
    emit?.("status", {
      message: `Fixing build error (${attempt}/${maxAttempts})…`,
      fixAttempt: attempt,
      maxFixAttempts: maxAttempts,
    });

    return runLlmEditPass(env, input, emit, {
      systemPrompt: buildFixSystemPrompt(),
      userPrompt: buildFixPrompt(input),
      strict: true,
    });
  }

  await requireApprovedDesignRequest(env, input, emit);

  return runLlmEditPass(env, input, emit, {
    systemPrompt: buildEditSystemPrompt(),
    userPrompt: buildEditPrompt(input),
    strict: true,
  });
}
